### ISSUE TITLE
MultiClusterService/ClusterDeployment should wait for ServiceTemplate to become VALID

### ISSUE THREAD

**Issue by denis-ryzhkov** [k0rdent/kcm#1137]
When we [replaced](https://github.com/k0rdent/kof/pull/109/files) Sevltos `ClusterProfile` installing `helmCharts` with `MultiClusterService` installing `serviceSpec.services[].template`, it started failing with:
```
admission webhook "validation.multiclusterservice.k0rdent.mirantis.com"
denied the request: the MultiClusterService is invalid:
the template is not valid:
the template is not valid:
```
and no other details.

This happens because the referenced `ServiceTemplate` is part of the same chart as this `MultiClusterService`, and while this `ServiceTemplate` is created first via `helm.sh/hook: pre-install`, it does not get `VALID` status (`kubectl get svctmpl -A`) instantly, so the admission webhook above fails.

A retry helps because the `ServiceTemplate` becomes `VALID` pretty fast.

Maybe the admission webhook could do a single retry after few seconds (single because the template may be just broken and never become `VALID`), or is there another solution?

Until this is fixed in the admission webhook, I'm adding `sleep 10` as a pre-install hook to `kof` [here](https://github.com/k0rdent/kof/blob/95bda64f4ee4b4c77dd7baca45dece44cf1d4890/charts/kof-mothership/templates/k0rdent/kof/wait-valid-svctmpl.yaml) as a workaround.

Maybe related: https://github.com/k0rdent/kcm/issues/871

---

From @Algeran :

Similar issue happens when I try to apply `ServiceTemplate` and patch `AccessManagement` object at the same time with this `ServiceTemplate` (template chain). Admission webhook rejects to patch access management object and I need to deploy service template and then patch access management. If I use some GitOps deployments, I need to separate sync of template objects and access management object, and configure dependency between them.

As a solution, I think admission webhook could pass `MultiClusterService` and `AccessManagement` objects with any values, but then during the reconciliation add information about missing templates to status and events.

**Comment by BROngineer** [comment]
@denis-ryzhkov I might be wrong, but for me it doesn't look correct to perform this kind of validation in a webhook at all. Like if k8s would check whether the image is available while validating pod during creation.
I'd vote for regular reconciliation and reflecting the state according to templates' status.

**Comment by denis-ryzhkov** [comment]
@BROngineer thank you, could you please elaborate how we could use reconciliation in this case: 
* User makes `helm install` of our chart.
* This chart contains few `ServiceTemplate`-s and `MultiClusterService` which uses these `ServiceTemplate`-s.
* `helm install` fails installing `MultiClusterService` because these `ServiceTemplate`-s are not `VALID` yet.

Could we do more efficient reconciliation instead of current [workaround](https://github.com/k0rdent/kof/blob/95bda64f4ee4b4c77dd7baca45dece44cf1d4890/charts/kof-mothership/templates/k0rdent/kof/wait-valid-svctmpl.yaml)?

**Comment by zerospiel** [comment]
The issue has been addressed though keep in mind this comment https://github.com/k0rdent/kcm/pull/1337#discussion_r2027190371 

That would be done as part of the #1236 

But at the moment nothing will block you from creating `servicetemplates` along with a `mcs`/`cld`

**Comment by denis-ryzhkov** [comment]
> But at the moment nothing will block you from creating `servicetemplates` along with a `mcs`/`cld`

* This is still not the case.
* How to reproduce:
```
git clone https://github.com/k0rdent/kcm.git
cd kcm
git checkout v1.4.0
make cli-install
make dev-apply

cat >test.yaml <<EOF
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hr1
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/managed: "true"
spec:
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplate
metadata:
  name: st1
  namespace: kcm-system
spec:
  helm:
    chartSpec:
      chart: ingress-nginx
      version: 4.13.3
      sourceRef:
        kind: HelmRepository
        name: hr1
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: mcs1
spec:
  serviceSpec:
    services:
      - name: s1
        namespace: kcm-system
        template: st1
EOF

kubectl apply -f test.yaml

  helmrepository.source.toolkit.fluxcd.io/hr1 created
  servicetemplate.k0rdent.mirantis.com/st1 created
  Error from server (Forbidden): error when creating "test.yaml":
  admission webhook "validation.multiclusterservice.k0rdent.mirantis.com" denied the request:
  the MultiClusterService is invalid:
  the ServiceTemplate kcm-system/st1 is invalid with the error:

kubectl get svctmpl -n kcm-system st1

  NAME   VALID
  st1  

kubectl get svctmpl -n kcm-system st1

  NAME   VALID
  st1    false

kubectl get svctmpl -n kcm-system st1 -o yaml

  ...
  status:
    chartRef:
      kind: HelmChart
      name: st1
      namespace: kcm-system
    chartVersion: 4.13.3
    valid: false

# Wait...

kubectl get svctmpl -n kcm-system st1

  NAME   VALID
  st1    true

kubectl apply -f test.yaml

  helmrepository.source.toolkit.fluxcd.io/hr1 unchanged
  servicetemplate.k0rdent.mirantis.com/st1 unchanged
  multiclusterservice.k0rdent.mirantis.com/mcs1 created

# Cleanup twice due to ServiceTemplate being in use by MCS, that is OK:
kubectl delete -f test.yaml
kubectl delete -f test.yaml
```
* Note there are still no error details in the `is invalid with the error:` line,
  it just ends with a `:` character.
* Could you please add the error details
  or replace it with `is invalid. Details: kubectl get svctmpl -n kcm-system st1 -o yaml`
  and add details to the `status` to explain why `valid: false` is there,
  for example `details: In progress, all good so far, please wait`,
  or an actual error message if it is final.
* To avoid this error we have 3-step workaround in https://docs.k0rdent.io/v1.4.0/admin/kof/kof-install/#management-cluster
  * `helm upgrade -i -n kof kof-mothership ...` to install `ServiceTemplates`.
  * Wait until the value of `VALID` changes to `true` for all `ServiceTemplate` objects:
    ```
    kubectl get svctmpl -A
    ```
  * `helm upgrade -i -n kof kof-regional ... kof-child ...` to install `MultiClusterServices` and avoid the error above.
* We've came to this 3-step workaround after failed attempts to automate it with pre-install hooks:
  * https://github.com/k0rdent/kof/pull/121
  * https://github.com/k0rdent/kof/pull/171
  * https://github.com/k0rdent/kof/pull/186
  * https://github.com/k0rdent/kof/pull/190
* Now we've got a requirement to provide https://github.com/k0rdent/kof/issues/503 and this 3-step workaround is **not simple** at all.
* We've faced it again today replacing `ClusterProfiles` with `MultiClusterServices` in https://github.com/k0rdent/kof/issues/392
* Please fix it again to avoid the manual wait step, to make the UX more simple.
