### ISSUE TITLE
[bug] kcm controller doesn't create release and crashes if `createManagement` is set to false

### ISSUE THREAD

**Issue by Algeran** [k0rdent/kcm#940]
**Describe the bug**
Deployed kcm-controller v0.0.7 with disabled default Management object creation. Controller pod fails to start, prints in logs a lot of errors and doesn't create the release object.

**To Reproduce**
1. Values:
    ```
    controller:
      createManagement: false
    ```
2. deploy kcm helm chart
3. monitor logs and pod status, check that release object is not created

**Expected behavior**
Controller should start and create release kcm-0-0-7 release object

**Additional context**

[controller.log](https://github.com/user-attachments/files/18508264/controller.log)

**Comment by kylewuolle** [comment]
I've tried with the latest code and this is now fixed:

1. `git checkout 5c0ce3213dfc2c989e9ee4efeb266d0ee34fb21b` (0.0.7 tag)
2. `make kind-deploy registry-deploy dev-push`
3. `helm install kcm oci://127.0.0.1:5001/charts/kcm  --version 0.0.7 -n kcm-system --create-namespace --set="controller.createManagement=false" --set="image.repository=localhost/kcm/controller"`
4. I get the same error as in the issue
5. `make dev-destroy`
6. `git checkout c486cd1fdcc5e9af4d68afe7c74ccce836459c5c` (current main revision)
7. `make kind-deploy registry-deploy dev-push`
8. `helm install kcm oci://127.0.0.1:5001/charts/kcm  --version 0.0.7 -n kcm-system --create-namespace --set="controller.createManagement=false" --set="image.repository=localhost/kcm/controller"`
9. It now works as expected

**Comment by Algeran** [comment]
Hi @kylewuolle ,
I started the controller from the main revision as you described. Controller is now not crushing, but it still doesn't create release object. So, it's not possible to create any custom Management object due to it requires to specify the release name. In operator pod logs I can see a lot of errors from all internal controllers that they can't find the Management object to backup. And I think this is the reason why the release object is not created as well:
https://github.com/k0rdent/kcm/blob/c486cd1fdcc5e9af4d68afe7c74ccce836459c5c/internal/controller/release_controller.go#L76

This condition blocks reconciliation loop in all controllers. Moreover, 
1. it's not clear why it tries to backup the management object with the `kcm` name. I understand, that this is the default name for the Management object that is created automatically, but I can create the custom one with any name, not `kcm`. And it will block the reconciliation process for all CRDs that managed by the operator.
2. Why the `Release` reconciliation loop includes the Management object backup logic. As far as I understand, the relation between release and management objects is inverse - you can't create and reconcile management object without fully deployed release.

**Comment by Algeran** [comment]
Added the log file from the controller pod

[controller.log](https://github.com/user-attachments/files/18573246/controller.log)

**Comment by zerospiel** [comment]
I believe the recent changes from #906 are related to the errors above. CC @Kshatrix

**Comment by ry4nz** [comment]
FYI this is currently blocking https://mirantis.jira.com/browse/BOP-1836

**Comment by eromanova** [comment]
@ry4nz There is another option to provide a custom Management configuration: 
1. Install k0rdent with `createManagement: true` (default)
2. Edit the `Management` object after the KCM installation `kubectl --kubeconfig <path-to-management-kubeconfig> edit management`

Would this approach work for your use case as a temporary workaround until the issue is resolved?
